### ISSUE TITLE
Dice roll to decide who has to get the fries

### ISSUE THREAD

**Issue by robbinjanssen** [trizz/frietbot#6]
Scenario:

> Robbin: @frietbot !volunteer
> Frietbot: Oke, ik roll de dobbelsteen, je hebt ...... 5!
> Tristen: @frietbot !volunteer
> Fietbot: Oke, ik roll de dobbelsteen, je hebt ...... 2!
> Robin (admin) @frietbot !afronden
> Frietbot: We ronden de bestelling af, ik heb het volgende genoteerd:
> ....
> En Tristan gaat het halen!

**Comment by trizz** [comment]
A dice roll or just let frietbot decide? Or let frietbot do a dice roll for all (available) users? If we work with volunteers, chances are that still the same volunteer has to go every week.
